# Generated by Django 5.2.3 on 2025-06-21 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('abbreviated', models.CharField(max_length=3, verbose_name='Сокращение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='images/classes/%m/%Y/%d/')),
                ('description', models.TextField(verbose_name='Описание класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Названине')),
                ('description', models.CharField(verbose_name='Описание')),
                ('abbreviation', models.CharField(max_length=1, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='DamageTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип урона',
                'verbose_name_plural': 'Типы урона',
            },
        ),
        migrations.CreateModel(
            name='Dices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Кость',
                'verbose_name_plural': 'Кости',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('weight', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Вес')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='MagicSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Школа магии',
                'verbose_name_plural': 'Школы магии',
            },
        ),
        migrations.CreateModel(
            name='WeaponsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Типы оружия')),
            ],
            options={
                'verbose_name': 'Тип оружия',
                'verbose_name_plural': 'Типы оружия',
            },
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количесво костей')),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_dice', to='guide.dices', verbose_name='Кость урона')),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_type', to='guide.dices', verbose_name='Тип урона')),
            ],
            options={
                'verbose_name': 'Урон',
                'verbose_name_plural': 'Уроны',
            },
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('using_time', models.CharField(verbose_name='Время накладывания')),
                ('distant', models.CharField(verbose_name='Дистанция')),
                ('material_components', models.CharField(blank=True, verbose_name='Материальные компоненты')),
                ('concentration', models.BooleanField(verbose_name='Концентрация')),
                ('spell_update', models.TextField(verbose_name='Улучшение заклинания')),
                ('components', models.ManyToManyField(to='guide.components', verbose_name='Компоненты')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.magicschools', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Пример использования')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.chars', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='SubClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('clas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_level', to='guide.classes', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Подкласс',
                'verbose_name_plural': 'Подклассы',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Номер уровня')),
                ('name', models.CharField(verbose_name='Название уровня')),
                ('description', models.TextField(verbose_name='Описание')),
                ('clas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='guide.classes', verbose_name='Класс')),
                ('subclass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclasses_level', to='guide.subclasses', verbose_name='Подкласс')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='DamageSpells',
            fields=[
                ('spells_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.spells')),
                ('damage', models.ManyToManyField(related_name='spell_damages', to='guide.damages', verbose_name='Урон')),
                ('damage_on_level', models.ManyToManyField(related_name='spell_damage_on_level', to='guide.damages', verbose_name='Урон за уровень')),
            ],
            options={
                'verbose_name': 'Боевое заклинание',
                'verbose_name_plural': 'Боевые заклинания',
            },
            bases=('guide.spells',),
        ),
        migrations.CreateModel(
            name='MagicFocuses',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.items')),
                ('classes', models.ManyToManyField(related_name='classes_focuses', to='guide.classes', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Фокусировка',
                'verbose_name_plural': 'Фокусировки',
            },
            bases=('guide.items',),
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.items')),
                ('usage', models.CharField(verbose_name='Использование')),
                ('creating', models.CharField(verbose_name='Создание')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_char', to='guide.chars', verbose_name='Характеристика')),
                ('creating_items', models.ManyToManyField(related_name='items_tools', to='guide.items', verbose_name='Создвание предметов')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
            bases=('guide.items',),
        ),
    ]
