# Generated by Django 5.2.3 on 2025-06-22 17:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория доспеха',
                'verbose_name_plural': 'Категории доспехов',
            },
        ),
        migrations.CreateModel(
            name='Armors',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.items')),
                ('ac', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Класс защиты')),
                ('ac_dex', models.IntegerField(default=0, verbose_name='Бонус ловкости')),
                ('min_power', models.IntegerField(blank=True, verbose_name='Минимум силы')),
                ('hide', models.BooleanField(verbose_name='Помеха скрытности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_category', to='guide.armorcategory', verbose_name='Категория доспеха')),
            ],
            options={
                'verbose_name': 'Доспех',
                'verbose_name_plural': 'Доспехи',
            },
            bases=('guide.items',),
        ),
        migrations.CreateModel(
            name='ClassesSkillsTableColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Столбец таблицы умений класса',
                'verbose_name_plural': 'Столбцы таблицы умений класса',
            },
        ),
        migrations.CreateModel(
            name='ClassesSkillsTableValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение таблицы умений класса',
                'verbose_name_plural': 'Значения таблицы умений класса',
            },
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.items')),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_damage', to='guide.damages', verbose_name='Урон')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружия',
            },
            bases=('guide.items',),
        ),
        migrations.CreateModel(
            name='WeaponsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория оружия',
                'verbose_name_plural': 'Категории оружия',
            },
        ),
        migrations.CreateModel(
            name='WeaponsClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Класс оружия',
                'verbose_name_plural': 'Классы оружия',
            },
        ),
        migrations.CreateModel(
            name='WeaponsFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Свойство оружия',
                'verbose_name_plural': 'Свойства оружия',
            },
        ),
        migrations.CreateModel(
            name='WeaponsTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Оружейные прием',
                'verbose_name_plural': 'Оружейные приемы',
            },
        ),
        migrations.DeleteModel(
            name='WeaponsTypes',
        ),
        migrations.AddField(
            model_name='classes',
            name='armors_text',
            field=models.CharField(default=1, verbose_name='Владение доспехами(текст)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='beginning_equipment',
            field=models.TextField(default=0, verbose_name='Старовое снаряжение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='hit_dice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='class_hit_dice', to='guide.dices', verbose_name='Кость хитов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='hits_on_first_level',
            field=models.IntegerField(default=1, verbose_name='Хиты на первом уровне'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='hits_on_next_levels',
            field=models.IntegerField(default=1, verbose_name='Хиты на следующих уровнях'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='main_chars',
            field=models.ManyToManyField(related_name='class_main_chars', to='guide.chars', verbose_name='Основные хар-ки'),
        ),
        migrations.AddField(
            model_name='classes',
            name='saving_throws',
            field=models.ManyToManyField(related_name='class_saving_throws', to='guide.dices', verbose_name='Спасброски'),
        ),
        migrations.AddField(
            model_name='classes',
            name='skills_list',
            field=models.ManyToManyField(related_name='class_skills', to='guide.skills', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='classes',
            name='skills_quantity',
            field=models.IntegerField(default=1, verbose_name='Количество навыков'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='spells_power',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Сила заклинаний'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='tools',
            field=models.ManyToManyField(related_name='class_tools', to='guide.tools', verbose_name='Владение инструментами'),
        ),
        migrations.AddField(
            model_name='classes',
            name='tools_text',
            field=models.CharField(default=1, verbose_name='Владение инструменатми(текст)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='weapons_text',
            field=models.CharField(default=1, verbose_name='Владение оружием(текст)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='armors',
            field=models.ManyToManyField(related_name='class_armors', to='guide.armorcategory', verbose_name='Владение инструментами'),
        ),
        migrations.AddField(
            model_name='classesskillstablecolumns',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_skill_table', to='guide.classes', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='classesskillstablevalues',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_value', to='guide.classesskillstablecolumns', verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_type', to='guide.weaponscategories', verbose_name='Категория оружия'),
        ),
        migrations.AddField(
            model_name='classes',
            name='weapons',
            field=models.ManyToManyField(related_name='class_weapons', to='guide.weaponscategories', verbose_name='Владение оружием'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_class', to='guide.weaponsclasses', verbose_name='Класс оружия'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='features',
            field=models.ManyToManyField(related_name='weapons_features', to='guide.weaponsfeatures', verbose_name='Свойства оружия'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='techniques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_technique', to='guide.weaponstechniques', verbose_name='Оружейный прием'),
        ),
    ]
