# Generated by Django 5.2.3 on 2025-06-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_armorcategory_armors_classesskillstablecolumns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='armors_text',
            field=models.CharField(blank=True, verbose_name='Владение доспехами(текст)'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='beginning_equipment',
            field=models.TextField(blank=True, verbose_name='Старовое снаряжение'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='saving_throws',
            field=models.ManyToManyField(related_name='class_saving_throws', to='guide.chars', verbose_name='Спасброски'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='tools_text',
            field=models.CharField(blank=True, verbose_name='Владение инструменатми(текст)'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='weapons_text',
            field=models.CharField(blank=True, verbose_name='Владение оружием(текст)'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='creating',
            field=models.CharField(blank=True, verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='creating_items',
            field=models.ManyToManyField(blank=True, related_name='items_tools', to='guide.items', verbose_name='Создвание предметов'),
        ),
    ]
